### ISSUE TITLE
error loading module  'socket.cx64'

### ISSUE THREAD

**Issue by haibanekun** [arpruss/raspberryjammod-minetest#2]
Hi!
I've got a problem starting Minetest with mod enabled.  The error is:

`2017-02-13 11:49:08: ERROR[Main]: ModError: Failed to load and run script from C:\Games\minetest-0.4.15-win64\bin\..\mods\raspberryjammod\init.lua:`
`2017-02-13 11:49:08: ERROR[Main]: error loading module 'socket.cx64' from file 'C:\Games\minetest-0.4.15-win64\bin\..\mods\raspberryjammod\socket\cx64.dll':`

Would you give any advise?
`

**Comment by arpruss** [comment]
I have not got around to compiling for 0.4.15. Use 0.4.13.

**Comment by haibanekun** [comment]
Thanks, it works fine in 0.4.13.
