### ISSUE TITLE
Convert Minecraft maps to Minetest worlds

### ISSUE THREAD

**Issue by Pantyhose-X** [arpruss/raspberryjammod-minetest#7]
system: Win10
versions: Minecraft Java

How do Convert Minecraft maps to Minetest worlds
Use Details Steps ?
https://forum.minetest.net/viewtopic.php?f=12&t=13709
https://forum.minetest.net/viewtopic.php?p=211743

**Comment by arpruss** [comment]
You can use RaspberryJamMod with Minecraft and a python script to export a region to a file, and then RaspberryJamMod and another python script to load the region back.
